- hosts: all
  become: true
  tasks:

    - name: Creating a '/opt/slackbot' directory
      file:
        path: /opt/slackbot
        state: directory

    - name: Upload the slackbot jar
      copy:
        src: ../../target/slackbot-1.0-SNAPSHOT-jar-with-dependencies.jar
        dest: /opt/slackbot/slackbot.jar
      notify: restart slackbot

    - name: creates the environment file for the service
      template:
        src: templates/slackbot.env.j2
        dest: /opt/slackbot/slackbot.env
        mode: '0600'
        owner: '{{ user_to_run_the_service }}'
      notify: restart slackbot

    - name: creates the jira-rest-client.properties file
      template:
        src: templates/jira-rest-client.properties.j2
        dest: /opt/slackbot/jira-rest-client.properties
        mode: '0600'
        owner: '{{ user_to_run_the_service }}'
      notify: restart slackbot

    - name: setup a systemd unit file
      template:
        src: "templates/slackbot.service.j2"
        dest: "/etc/systemd/system/slackbot.service"
      notify: restart slackbot

  handlers:
    - name: restart slackbot
      systemd:
        state: restarted
        daemon_reload: yes
        name: slackbot
